permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

excerpt_separator: "<!-- more -->"

paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "ZHUANGZHUANG"
email: "mail@zhuangzhuang.ml"
description: ""
logo: "https://raw.githubusercontent.com/ydzydzydz/blogphoto/master/avatar.png"
github_username:  "ydzydzydz"


plugins: [jekyll-paginate]


url: "https://zhuangzhuang.cf"
imgrepo: "https://zhuangzhuang.cf/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

friends:
  - tittle: å…±äº«èµ„æºç«™ç‚¹
    url: http://www.gxzyzd.com/
    img: http://www.gxzyzd.com/images/slider4.jpg
    time: 2019.01
    description: å› ç¼˜è€Œé‡ï¼Œä¸”è¡Œä¸”çæƒœ
  - tittle: Newlearnerã®å°ç«™
    url: https://www.newlearner.site/
    img: https://www.newlearner.site/â€œwp-content/uploadsâ€/2018/12/QQ20181226-001616@2x.jpg
    time: 2019.03.06
    description: æ¢ç´¢æœªçŸ¥ï¼Œè®°å½•ç‚¹æ»´
  - tittle: æ–¹å¯¸é—´
    url: https://withdewhua.space/blog/
    img: img/1.png
    time: 2019.04.23
    description: èŠ±å¼€å ªæŠ˜ç›´é¡»æŠ˜ï¼Œè«å¾…æ— èŠ±ç©ºæŠ˜æ
  - tittle: MOS
    url: http://www.arman.store
    img: img/2.png
    time: 2019.04
    description: å’¸é±¼åšä¸»ï¼Œä¸å®šæœŸæ›´æ–°ä¸€äº›æœ‰æ„æ€çš„å†…å®¹
  - tittle: å…±äº«èµ„æºç«™ç‚¹è®ºå›
    url: https://bbs.gxzyzd.com/
    img: http://www.gxzyzd.com/images/slider1.jpg
    time: 2019.07.08
    description: å’¸é±¼é˜¿æ°¸ï¼Œè¿˜æ²¡å†™ç®€ä»‹





share: true
donate: true



valine:
  -
    appid: edBPYFEXGjTNmYOSU6QfSs8M-gzGzoHsz
    appkey: Ak42WeKa9Fx00j5RiUXUJIhK
    placeholder: è¯„è®ºå‰è¯·åŠ¡å¿…ç•™ä¸‹çœŸå®é‚®ç®±ï¼Œæ–¹ä¾¿æ¥æ”¶å›å¤é‚®ä»¶ ğŸ˜˜
